### ISSUE TITLE
Nothing happened when user didn't install "Permission Nanny"

### ISSUE THREAD

**Issue by pcqpcq** [littledot/Permission-Nanny#1]
I think Permission Nanny is a good idea.
it will be useful if all developers follow the rules.

---

but, nothing happened when user didn't install "Permission Nanny", any toast or dialog are not shown.
it will let the user confusion.

---

how about show a dialog to show the way to install "Permission Nanny"?

**Comment by littledot** [comment]
I try not to add any UI code into the SDK because I do not feel confident I know the desired flow for client apps, especially when the narrative is from them. For example, a Dialog may sound reasonable to you, but another may prefer Snackbars.

Hence all I did was include a convenience method for clients to check if the server is installed on the device (in NannyClient.java).

One thing I should definitely do is return a 404 Not Found immediately when the server is not installed. As for the UI, I'll need to consider your proposal for showing a dialog.

**Comment by pcqpcq** [comment]
em, i think you are right.
what you have did now is a good choice :+1:
